### ISSUE TITLE
T05b.03 Bug with loading indicator

### ISSUE THREAD

**Issue by artem-p** [udacity/ud851-Exercises#106]
After performing a search, when I hide application with home button and unhide again, loading indicator appears and never stops. It can be fixed, by adding `mLoadingIndicator.setVisibility(View.INVISIBLE);` before deliver result.

**Comment by cristianberroeta** [comment]
Yes. I debugged the code, and in fact our **deliverResult(mGithubJson)** call isn't causing our **onLoadFinished(Loader<String> loader, String data)** to be called back. I think that happens, because the reference that we are passing into **deliverResults** is the same that the **LoaderManager** already had associated to the **Loader**, as you can see in:
[https://github.com/android/platform_frameworks_base/blob/master/core/java/android/app/LoaderManager.java#L453](https://github.com/android/platform_frameworks_base/blob/master/core/java/android/app/LoaderManager.java#L453)

in the line that says **if (mData != data || !mHaveData) {**

So your fix works nice. And additionally, one should be aware that **onLoadFinished** is not going to be called if the reference passed to **deliverResults** "is the same as before". If you would like that **onLoadFinished** was called, instead of calling **deliverResult(mGithubJson)** in **onStartLoading** (when **mGithubJson** isn't null), you should call **deliverResult(new String(mGithubJson))**, passing a reference to a new object with the same content as the old object, instead of passing a reference to the old object. As the code in LoaderManager.java is comparing two objects using the **!=** operator, and now we are creating a new object (that conveniently has the same content that the other one), that comparison yields true (the references are different), and **onLoadFinished** gets called back.

**Comment by chrisdziewa** [comment]
I did what @artem-p  did as well. I like your solution @cristianberroeta. I only wish I wouldn't get a warning for a redundant string while doing so. Guess I will just suppress it ha.

**Comment by johnshea** [comment]
Fixed.
