### ISSUE TITLE
T04b.02 UriBuilder.path issue

### ISSUE THREAD

**Issue by ab316** [udacity/ud851-Exercises#182]
Using UriBuilder.path("0,0") encodes the string so that it becomes "0%20".
Shouldn't we use UriBuilder.encodedPath("0,0") that retains the string as it is?

**Comment by PhilippHGerber** [comment]
it should be like this:

Uri.Builder builder = new Uri.Builder();
builder.scheme("geo")
        .appendPath("0,0")
        .appendQueryParameter("q", addressString);
Uri addressUri = builder.build();

Thanks to https://stackoverflow.com/a/44222951

**Comment by gameman15** [comment]
@PhGerber this is not correct since appendPath still sanitizes the input. ("geo:0%20")

encodedPath also produces an incorrect output as it gives "geo:/0,0" (inserting a /).

Also if you go `Uri.parse("geo:0,0").buildUpon().appendQueryParameter("q", addressString);` appendQueryParameter strips the 0,0 for some reason and you get something like "geo:?q=myQuery" so I think maybe they should move away from using UriBuilder here at all

**Comment by johnshea** [comment]
Fixed.
