### ISSUE TITLE
Toy Repository

### ISSUE THREAD

**Issue by US18** [udacity/ud851-Exercises#219]
How to open the existing android project in Android Studio 2.3.3 ? Please Reply...

**Comment by AlexBordei** [comment]
Hi US18,

Can you be more specific about what project do you want to open?
If you are referring to the Sunshine app or the Toy List app I think there is no complete app package that you can import. In this repo, you will be able to find committed scripts and resources related to the work and exercises that should be done in order to obtain the apps mentioned in courses.

Let me know that if this helps you.

Alex

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
