### ISSUE TITLE
T02.01 - Exercise: connot resolve method findViewById

### ISSUE THREAD

**Issue by ishayw** [udacity/ud851-Exercises#381]
during T02.01 excercise while using findViewById android studio is notifying me of the message
connot resolve method findViewById

opened the solution project and the same happens without any changes by me

![image](https://user-images.githubusercontent.com/3840826/41809813-85626a82-76fc-11e8-8dba-daebc694d3c8.png)

**Comment by 1996shivm** [comment]
check  the package name
you will find the package name ablove of your class declaration
compare it with the package name that you had declared  in your manifest
file
if it still give you the same error after fixing the package name then send
me the screenshot of  that error message or you can also send me your code

**Comment by khahani** [comment]
Open build.gradle (Module:app) and replace "compile" with "implementation".
sync project again.

**Comment by rasik210** [comment]
Most interesting part of this issue is that, even though so many methods aren't resolvable but the project still builds successfully without any error. Here are the steps I took to resolve the issue:

1. Close the project. 
2. Delete `.idea` directory present in the root directory of the project.
3. Do a search of all the files with extension `.iml`. Delete them all. I generally find 2-3 such files.
4. Reopen the project
5. Sync project with Gradle files and rebuild the project.

You are all set! I figured out the solution from [this](https://stackoverflow.com/a/21100896/465053) SO thread. 

@ishayw Can you please try this resolution? Hope this helps!

**Comment by johnshea** [comment]
Please try the above suggestions as we are unable to troubleshoot individual errors.
