### ISSUE TITLE
Build Errors on Mac

### ISSUE THREAD

**Issue by RobertBonagura** [udacity/ud851-Exercises#420]
I have been getting all sorts of build errors when i try opening any of the projects.

I loooked in the project files I had been trying to open and realized that some of the files contain .bat files... which i dont think i can run on my mac. Is there anyone using Android Studio on a mac without any problem?

**Comment by ghost** [comment]
I use android studio on windows, but I have a lot of friends who run it on mac and it works perfectly fine. Check that your internet connection is active when you want to build, so that the  dependencies and gradle files can be synced correctly. Then look up the errors in your log files and go online for help. Try stackoverflow for the errors.

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
