### ISSUE TITLE
T03.03-Exercise-RecyclerViewAdapter incorrect variable name

### ISSUE THREAD

**Issue by ErikTillberg** [udacity/ud851-Exercises#50]
```
public NumberViewHolder(View view) {
            super(itemView);

            listItemNumberView = (TextView) itemView.findViewById(R.id.tv_item_number);
        }
```
itemView should be just 'view' (or other way around).

**Comment by btamimi** [comment]
it's just a variable name .. no worries :)

**Comment by alibitek** [comment]
We should worry, otherwise the compiler will worry for us, aka will not compile the starting exercise code :-) 

@ErikTillberg I think you have an older version of the code. Try to run a git pull or redownload the zip if you didn't clone the repo.
git blame says that that part of the code was changed last year in November
```
2277f88b (Lyla       2016-11-09 22:33:32 -0800 84)         public NumberViewHolder(View itemView) {
2277f88b (Lyla       2016-11-09 22:33:32 -0800 85)             super(itemView);
2277f88b (Lyla       2016-11-09 22:33:32 -0800 86)
2277f88b (Lyla       2016-11-09 22:33:32 -0800 87)             listItemNumberView = (TextView) itemView.findViewById($
2277f88b (Lyla       2016-11-09 22:33:32 -0800 88)         }
```
and it looks good to me.

**Comment by johnshea** [comment]
Code was changed as stated. Issue is resolved.
