### ISSUE TITLE
T04b.02-Exercise-OpenMap example solution not working

### ISSUE THREAD

**Issue by jankalfus** [udacity/ud851-Exercises#70]
The example solution is not working the way it should. It opens Google Maps, but not at the location specified.

In the example solution, the query parameter is added using the `.query()` method of `Uri.Builder`. This has no effect. [The documentation specifies that the query parameter must have a key of "q"](https://developer.android.com/guide/components/intents-common.html#Maps).

So the solution is to use the `.appendQueryParameter()` method, specifying "q" as the key:

```
public void onClickOpenAddressButton(View v) {
    Uri.Builder builder = new Uri.Builder();
    builder.scheme("geo")
            .path("0,0")
            .appendQueryParameter("q", "Mountain View");
    showMap(builder.build());
}
```

**Comment by alibitek** [comment]
Indeed, using Uri.Builder doesn't work for opaque URIs, for more details see [here](https://stackoverflow.com/questions/2662531/launching-google-maps-directions-via-an-intent-on-android/41780174#comment71522260_41780174)

The above code you suggested outputs the following URI: `geo:/0%2C0?q=Mountain%20View` , which looks incorrect to me, due to the extra slash and the percent encoding of the 0,0 opaque part, but Google Maps I think handles this error. Other maps and navigation apps might not.

**Comment by jankalfus** [comment]
So the correct way to do this would be `Uri.parse("geo:0,0?q=" + Uri.encode("Mountain View"))`?

**Comment by lednhatkhanh** [comment]
@jankalfus Yes, I use the `Uri.parse` and it works

**Comment by buthainahhamdy** [comment]
i have the same problem , but i used Uri.parse  and it works

**Comment by l-RUS-l** [comment]
I have the same problem and use same solution

**Comment by m-chichikalov** [comment]
Yep, had the same problem. Found this page while wa looking for answers... 
Using Log gave me a hint.   Uri.parse() helps me.

**Comment by RaffiRincon** [comment]
Google recommends using Map URLs.

Source: https://developers.google.com/maps/documentation/android-api/intents

**Comment by waciumawanjohi** [comment]
@RaffiRincon True statement. But using a Google Map URL forces the enduser to Google Maps, rather than allowing the user to use the mapping application of their choice.

**Comment by johnshea** [comment]
Fixed.
